### PR TITLE
Travis CI requires Trusty for hhvm testing

### PR DESCRIPTION
**Pull request by jakejohns**

### CODE REVIEW

**Comment by jakejohns** [comment]
*bump* @pmjones

**Comment by jakejohns** [comment]
@harikt @pmjones anybody? ...

**Comment by harikt** [comment]
Hi,

All looks good. But I am not a maintainer , so I will not be able to merge.

Thank you.

**Comment by jakejohns** [comment]
My mistake, @harikt. I thought you were a maintainer here for some reason. Thanks.

**Comment by cxj** [comment]
I want to update to PHP 7.1 as a minimum, I think.  Should that become a Radar 2.0 branch?  One could argue it's a major change.  Also, do we want to continue supporting HHVM?  I thought I read somewhere in one of Paul's projects where he had decided to drop it.  (I'll go search for that.)

**Comment by cxj** [comment]
HHVM dropped support for PHP with the 4.0 release in February, 2019.  I've updated the Travis configuration to drop HHVM completely, so I think that obviates the need for this PR.

**Pull request closed without merging**
