### PR TITLE
Decode incoming JSON requests.

### PR DESCRIPTION
**Pull request by galactic-void**
Decode incoming (POST, PUT, PATCH, etc) JSON requests.

### CODE REVIEW

**Comment by pmjones** [comment]
Aha! This is a classic use for a middleware handler. This makes me wonder if we need a middleware repo, or at least a wiki page to point to middleware. @galactic-void you get where I'm coming from?

**Comment by pmjones** [comment]
@galactic-void Would you feel like converting this to a PR on https://github.com/relayphp/Relay.Middleware as a middleware piece?

**Comment by varunjoshi12** [comment]
Hi anybody please help me i  have to get lat long in php from this json  Data

{
   "results" : [
      {
         "address_components" : [
            {
               "long_name" : "Indore",
               "short_name" : "Indore",
               "types" : [ "locality", "political" ]
            },
            {
               "long_name" : "Indore",
               "short_name" : "Indore",
               "types" : [ "administrative_area_level_2", "political" ]
            },
            {
               "long_name" : "Madhya Pradesh",
               "short_name" : "MP",
               "types" : [ "administrative_area_level_1", "political" ]
            },
            {
               "long_name" : "India",
               "short_name" : "IN",
               "types" : [ "country", "political" ]
            }
         ],
         "formatted_address" : "Indore, Madhya Pradesh, India",
         "geometry" : {
            "bounds" : {
               "northeast" : {
                  "lat" : 22.8485735,
                  "lng" : 75.965395
               },
               "southwest" : {
                  "lat" : 22.6076326,
                  "lng" : 75.7411195
               }
            },
            "location" : {
               "lat" : 22.7195687,
               "lng" : 75.8577258
            },
            "location_type" : "APPROXIMATE",
            "viewport" : {
               "northeast" : {
                  "lat" : 22.8485735,
                  "lng" : 75.965395
               },
               "southwest" : {
                  "lat" : 22.6076326,
                  "lng" : 75.7411195
               }
            }
         },
         "place_id" : "ChIJ2w1BG638YjkR9EBiNdrEbgk",
         "types" : [ "locality", "political" ]
      }
   ],
   "status" : "OK"
}

**Comment by pmjones** [comment]
@varunjoshi12 Sorry, this is not a support thread.

**Comment by jakejohns** [comment]
this can likely be closed re: relayphp/Relay.Middleware#3

**Pull request closed without merging**
