### PR TITLE
Use class constants and ::class

### PR DESCRIPTION
**Pull request by jakejohns**
I like using the class constants for the service and attributes names because it feels less like guessing magic strings.  To be honest, I often actually just use fully qualified class names for these identifiers, eg `$di->set(Adr::class, $di->lazyNew(Adr::class));`, since for the most part i don't have multiple instances of a class defined as a service or set as an attribute on a request. I also think it helps more accurately express the 'coupling'/'dependency'/'relation' that exists, looks nicer, and more clearly expresses whats going on.

### CODE REVIEW

**Comment by elazar** [comment]
Not sure if it's worth noting, but all of Radar's present Composer dependencies save for `relay/middleware` explicitly require PHP 5.5 or higher in `composer.json` while Radar itself has no explicit PHP version requirement. Implementing these changes would impose an implicit 5.5 requirement since [`::class` was introduced in that version](http://php.net/manual/en/language.oop5.basic.php#language.oop5.basic.class.class). This may be a requirement best made explicit in `composer.json` as part of this PR if it is merged.

**Comment by jakejohns** [comment]
Good point, @elazar. I had just checked the travis config to see whats being tested. But didnt think of the composer requirement for some reason. It appears that travis is only configured to check for 5.5, hvvm, and 7. Although it also seems unhappy still...

**Comment by elazar** [comment]
@jakejohns I'm not sure why, but on master, the [Travis job for PHP 7 is using PHPUnit 5.x](https://travis-ci.org/radarphp/Radar.Adr/jobs/169057684#L194). On your branch, the same job is using PHPUnit 6.0, where class names were changed to switch to namespaces and PHP 5.6 support was dropped. That's why the Travis job for 5.6 passes, but the ones for other versions fail.

Offhand, I can think of two different things to try to get the build to pass:

1. Change the PHP version requirement in `composer.json` from `5.6` to `5.5`.
2. Lock the PHPUnit version to `5.*` in `composer.json`.

**Comment by jakejohns** [comment]
@elazar I think my PR in #33 fixes travis, no?

**Comment by elazar** [comment]
@jakejohns Appears so, though I think it'll take getting #33 merged and this PR rebased against master after that to be 100% certain.

**Comment by cxj** [comment]
I think I'd like to see this project updated to require PHP 7.1 as a minimum.  I believe that means the PHPUnit version has to change, and likewise the parent class name for the tests.

**Comment by cxj** [comment]
I've branched Radar and the 2.x branch will require PHP 7.1 or better.  The 1.x branch will continue to support PHP 5.6 or better.

**Review by cxj — COMMENTED** [review]
I like this idea, because it allows smart editors and IDEs to help cross reference the symbols being used.  It also avoids faulty human guesses as to what the correct string is when looking for it in other places.

**Pull request merged**
